import { PageHero } from "@/components/marketing/PageHero";
import { PageContent } from "@/components/marketing/PageContent";
import { Sparkles, Dna, RefreshCw } from "lucide-react";

export const metadata = {
    title: "AI Itineraries | VoyageAI",
    description: "Personalized day-by-day itineraries generated by AI, tailored to your Travel DNA and preferences.",
};

export default function AIItinerariesPage() {
    return (
        <>
            <PageHero
                title="AI Itineraries"
                subtitle="Day-by-day plans generated by AI, tailored to your style, pace, and interests."
            />
            <PageContent>
                <p>
                    VoyageAI uses Groq LLaMA-3.3 and Google Gemini to generate intelligent itineraries. Your Travel DNA—travel style, pace, interests, and budget—shapes every suggestion.
                </p>
                <div className="space-y-6 mt-8">
                    {[
                        {
                            icon: Dna,
                            title: "Travel DNA",
                            desc: "Onboarding captures your preferences: adventure vs. luxury, fast vs. slow pace, food vs. history. The AI uses this to personalize every itinerary.",
                        },
                        {
                            icon: Sparkles,
                            title: "Context-Aware Generation",
                            desc: "The AI considers your trip dates, destination, group size, and dietary needs. It pulls from real data via Google Places and Amadeus for accurate suggestions.",
                        },
                        {
                            icon: RefreshCw,
                            title: "Re-optimize Anytime",
                            desc: "Not happy with a day? Re-optimize with one click. Add constraints, swap activities, or ask the AI to try a different style.",
                        },
                    ].map(({ icon: Icon, title, desc }) => (
                        <div
                            key={title}
                            className="flex gap-4 p-6 rounded-xl bg-white/[0.03] border border-white/5"
                        >
                            <Icon className="w-8 h-8 text-indigo-400 shrink-0" />
                            <div>
                                <h3 className="text-lg font-semibold text-white mb-2">{title}</h3>
                                <p className="text-slate-400 text-sm">{desc}</p>
                            </div>
                        </div>
                    ))}
                </div>
            </PageContent>
        </>
    );
}
