"use client";

import { useState, useCallback, useRef } from "react";
import { AnimatePresence, motion } from "framer-motion";
import {
    X,
    Share2,
    FileText,
    Instagram,
    BookOpen,
    AlignLeft,
    Copy,
    Check,
    Link2,
    RefreshCw,
    Printer,
    Loader2,
    Sparkles,
    Trash2,
    ExternalLink,
    Globe,
} from "lucide-react";
import { getCsrfToken } from "@/lib/api";
import type { TripDTO } from "@/lib/services/trips";
import type { Itinerary } from "@/lib/ai/schemas";

// ─── Types ────────────────────────────────────────────────────────────────────

type Tab = "share" | "pdf" | "instagram" | "blog" | "summary";

interface ExportDrawerProps {
    trip:         TripDTO;
    rawItinerary: Itinerary | null;
    onClose:      () => void;
}

// ─── PDF generation (client-side print window) ────────────────────────────────

function buildPrintHTML(trip: TripDTO, itinerary: Itinerary | null): string {
    const days = itinerary?.days ?? [];
    const dayRows = days.map(day => {
        const acts = day.activities.map(a =>
            `<tr><td style="padding:6px 12px;color:#aaa;font-size:11px;">${a.startTime}</td>
             <td style="padding:6px 12px;font-size:12px;">${a.name}</td>
             <td style="padding:6px 12px;color:#aaa;font-size:11px;">${a.location.name}</td>
             <td style="padding:6px 12px;color:#aaa;font-size:11px;text-align:right;">${trip.budget.currency} ${a.estimatedCost.amount.toFixed(0)}</td></tr>`
        ).join("");
        return `<div style="margin-bottom:24px;break-inside:avoid;">
            <div style="background:#1a1f29;padding:10px 16px;border-radius:8px;margin-bottom:8px;">
                <span style="font-size:11px;font-weight:700;color:#10B981;margin-right:8px;">DAY ${day.day}</span>
                <span style="font-weight:600;">${day.theme}</span>
                <span style="color:#666;font-size:11px;margin-left:8px;">${day.date}</span>
            </div>
            <table style="width:100%;border-collapse:collapse;">${acts}</table>
        </div>`;
    }).join("");

    const totalCost = itinerary?.totalEstimatedCost.amount ?? 0;
    const insights  = (itinerary?.aiInsights ?? []).slice(0, 3).map(i => `<li style="margin-bottom:6px;color:#aaa;font-size:12px;">${i}</li>`).join("");

    return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>${trip.destination} — VoyageAI</title>
<style>
  * { margin:0; padding:0; box-sizing:border-box; }
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; background:#0d1117; color:#e6edf3; padding:32px 40px; max-width:960px; margin:0 auto; }
  @media print {
    body { background: white; color: #111; padding: 20px; }
    .no-print { display: none; }
    * { color-adjust: exact; -webkit-print-color-adjust: exact; }
  }
</style>
</head>
<body>
  <div style="display:flex;align-items:center;justify-content:space-between;padding-bottom:24px;border-bottom:1px solid #21262d;margin-bottom:32px;">
    <div>
      <div style="font-size:11px;font-weight:700;letter-spacing:.1em;color:#10B981;text-transform:uppercase;margin-bottom:4px;">AI-Crafted Travel Plan</div>
      <h1 style="font-size:28px;font-weight:900;letter-spacing:-1px;">${trip.destination}</h1>
      <p style="color:#666;margin-top:4px;font-size:13px;">${trip.dates} &nbsp;·&nbsp; ${days.length} days</p>
    </div>
    <div style="text-align:right;">
      <div style="font-size:11px;color:#666;text-transform:uppercase;font-weight:700;letter-spacing:.08em;">Est. Cost</div>
      <div style="font-size:22px;font-weight:900;color:#10B981;">${trip.budget.currency} ${totalCost.toLocaleString()}</div>
    </div>
  </div>

  ${dayRows}

  ${insights ? `<div style="margin-top:32px;padding:16px;background:#1a1f29;border-radius:8px;border-left:3px solid #6366f1;">
    <div style="font-size:11px;font-weight:700;color:#6366f1;margin-bottom:10px;text-transform:uppercase;letter-spacing:.08em;">AI Insights</div>
    <ul style="list-style:disc;padding-left:18px;">${insights}</ul>
  </div>` : ""}

  <div style="margin-top:40px;padding-top:16px;border-top:1px solid #21262d;font-size:11px;color:#555;">
    Generated by VoyageAI &nbsp;·&nbsp; voyageai.app
  </div>
</body>
</html>`;
}

function triggerPrint(trip: TripDTO, itinerary: Itinerary | null) {
    const html = buildPrintHTML(trip, itinerary);
    const win = window.open("", "_blank", "width=900,height=700");
    if (!win) return;
    win.document.open();
    win.document.write(html);
    win.document.close();
    win.addEventListener("load", () => { win.focus(); win.print(); });
}

// ─── CopyButton helper ────────────────────────────────────────────────────────

function CopyButton({ text, className = "" }: { text: string; className?: string }) {
    const [copied, setCopied] = useState(false);
    const copy = useCallback(() => {
        navigator.clipboard.writeText(text).then(() => {
            setCopied(true);
            setTimeout(() => setCopied(false), 2000);
        });
    }, [text]);
    return (
        <button
            onClick={copy}
            className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium transition-colors ${
                copied ? "bg-emerald-500/20 text-emerald-400 border border-emerald-500/30" : "bg-white/[0.05] border border-white/[0.08] text-white/50 hover:text-white hover:bg-white/[0.08]"
            } ${className}`}
        >
            {copied ? <Check className="w-3 h-3" /> : <Copy className="w-3 h-3" />}
            {copied ? "Copied!" : "Copy"}
        </button>
    );
}

// ─── AI content tab ───────────────────────────────────────────────────────────

interface AITabProps {
    tripId:      string;
    format:      "instagram" | "blog" | "summary";
    destination: string;
    dates:       string;
    days:        number;
    budget?:     number;
    currency?:   string;
    highlights:  string[];
}

function AIContentTab({ tripId, format, destination, dates, days, budget, currency, highlights }: AITabProps) {
    const [content, setContent]   = useState("");
    const [loading, setLoading]   = useState(false);
    const [error, setError]       = useState<string | null>(null);
    const readerRef               = useRef<ReadableStreamDefaultReader<Uint8Array> | null>(null);

    const generate = useCallback(async () => {
        if (loading) return;
        setLoading(true);
        setContent("");
        setError(null);

        try {
            const res = await fetch("/api/ai/export", {
                method:  "POST",
                headers: {
                    "Content-Type": "application/json",
                    "X-CSRF-Token": getCsrfToken(),
                },
                body: JSON.stringify({ format, destination, dates, days, budget, currency, highlights }),
            });

            if (!res.ok) {
                const j = await res.json().catch(() => null);
                throw new Error(j?.error?.message ?? `Generation failed (${res.status})`);
            }

            if (!res.body) throw new Error("No stream body");

            const reader = res.body.getReader();
            readerRef.current = reader;
            const decoder = new TextDecoder();
            let text = "";

            while (true) {
                const { done, value } = await reader.read();
                if (done) break;
                text += decoder.decode(value, { stream: true });
                setContent(text);
            }
        } catch (err) {
            setError(err instanceof Error ? err.message : "Generation failed");
        } finally {
            setLoading(false);
            readerRef.current = null;
        }
    }, [format, destination, dates, days, budget, currency, highlights, loading]);

    void tripId; // used for rate-limiting context but sent via auth header

    return (
        <div className="space-y-3">
            {/* Generate button */}
            <div className="flex items-center gap-2">
                <button
                    onClick={generate}
                    disabled={loading}
                    className="flex items-center gap-2 px-4 py-2 rounded-xl bg-violet-500/15 border border-violet-500/25 text-violet-300 hover:bg-violet-500/25 text-sm font-semibold transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
                >
                    {loading ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <Sparkles className="w-3.5 h-3.5" />}
                    {loading ? "Generating…" : content ? "Regenerate" : "Generate with AI"}
                </button>
                {content && <CopyButton text={content} />}
            </div>

            {/* Error */}
            {error && (
                <p className="text-xs text-rose-400/80 bg-rose-500/[0.06] border border-rose-500/15 rounded-lg px-3 py-2">{error}</p>
            )}

            {/* Content area */}
            <div className="relative">
                <textarea
                    value={content}
                    onChange={e => setContent(e.target.value)}
                    placeholder={loading ? "" : `Click "Generate with AI" to create your ${format === "instagram" ? "Instagram caption" : format === "blog" ? "travel blog post" : "trip summary"}…`}
                    rows={format === "blog" ? 18 : format === "summary" ? 5 : 8}
                    className="w-full bg-white/[0.03] border border-white/[0.07] rounded-xl px-4 py-3 text-sm text-white/80 placeholder-white/20 resize-none focus:outline-none focus:border-violet-500/40 leading-relaxed font-mono"
                />
                {loading && content.length === 0 && (
                    <div className="absolute inset-0 flex items-center justify-center">
                        <div className="flex items-center gap-2 text-white/30 text-sm">
                            <Loader2 className="w-4 h-4 animate-spin" />
                            Writing your {format === "blog" ? "blog post" : format}…
                        </div>
                    </div>
                )}
                {loading && (
                    <div className="absolute bottom-3 right-3 w-1.5 h-4 bg-violet-400/70 animate-pulse rounded-sm" />
                )}
            </div>

            {format === "instagram" && content && (
                <p className="text-[10px] text-white/25 text-right tabular-nums">
                    {content.length} characters
                </p>
            )}
        </div>
    );
}

// ─── Share tab ────────────────────────────────────────────────────────────────

function ShareTab({ tripId }: { tripId: string }) {
    const [shareToken,  setShareToken]  = useState<string | null>(null);
    const [generating,  setGenerating]  = useState(false);
    const [revoking,    setRevoking]    = useState(false);
    const [confirmRevoke, setConfirmRevoke] = useState(false);
    const [error,       setError]       = useState<string | null>(null);
    const [copiedUrl,   setCopiedUrl]   = useState(false);

    const shareUrl = shareToken
        ? `${typeof window !== "undefined" ? window.location.origin : ""}/share/${shareToken}`
        : null;

    const generate = useCallback(async () => {
        setGenerating(true);
        setError(null);
        try {
            const res = await fetch(`/api/trips/${tripId}/share`, {
                method: "POST",
                headers: { "X-CSRF-Token": getCsrfToken() },
            });
            const j = await res.json();
            if (!j.success) throw new Error(j.error?.message ?? "Failed");
            setShareToken(j.data.shareToken);
        } catch (err) {
            setError(err instanceof Error ? err.message : "Failed to generate link");
        } finally {
            setGenerating(false);
        }
    }, [tripId]);

    const revoke = useCallback(async () => {
        setRevoking(true);
        setError(null);
        try {
            const res = await fetch(`/api/trips/${tripId}/share`, {
                method: "DELETE",
                headers: { "X-CSRF-Token": getCsrfToken() },
            });
            const j = await res.json();
            if (!j.success) throw new Error(j.error?.message ?? "Failed");
            setShareToken(null);
            setConfirmRevoke(false);
        } catch (err) {
            setError(err instanceof Error ? err.message : "Failed to revoke link");
        } finally {
            setRevoking(false);
        }
    }, [tripId]);

    const copyUrl = useCallback(() => {
        if (!shareUrl) return;
        navigator.clipboard.writeText(shareUrl).then(() => {
            setCopiedUrl(true);
            setTimeout(() => setCopiedUrl(false), 2000);
        });
    }, [shareUrl]);

    return (
        <div className="space-y-5">
            {/* Description */}
            <div className="flex items-start gap-3 p-4 rounded-xl bg-emerald-500/[0.05] border border-emerald-500/20">
                <Globe className="w-5 h-5 text-emerald-400 shrink-0 mt-0.5" />
                <div>
                    <p className="text-sm font-semibold text-white/80">Public Share Link</p>
                    <p className="text-xs text-white/40 mt-1 leading-relaxed">
                        Anyone with the link can view a read-only version of this trip — no sign-in required.
                    </p>
                </div>
            </div>

            {/* Generate or show URL */}
            {!shareToken ? (
                <button
                    onClick={generate}
                    disabled={generating}
                    className="w-full flex items-center justify-center gap-2 py-3 rounded-xl bg-emerald-500/15 border border-emerald-500/25 text-emerald-300 hover:bg-emerald-500/25 text-sm font-semibold transition-colors disabled:opacity-50"
                >
                    {generating ? <Loader2 className="w-4 h-4 animate-spin" /> : <Link2 className="w-4 h-4" />}
                    {generating ? "Generating…" : "Generate Share Link"}
                </button>
            ) : (
                <div className="space-y-3">
                    {/* URL field */}
                    <div className="flex items-center gap-2 bg-white/[0.03] border border-white/[0.08] rounded-xl px-4 py-2.5">
                        <Link2 className="w-3.5 h-3.5 text-emerald-400 shrink-0" />
                        <span className="flex-1 text-xs text-emerald-300 font-mono truncate">{shareUrl}</span>
                        <button
                            onClick={copyUrl}
                            className={`flex items-center gap-1.5 px-2.5 py-1 rounded-lg text-xs font-medium transition-colors shrink-0 ${
                                copiedUrl ? "bg-emerald-500/20 text-emerald-400" : "bg-white/[0.06] text-white/50 hover:text-white"
                            }`}
                        >
                            {copiedUrl ? <Check className="w-3 h-3" /> : <Copy className="w-3 h-3" />}
                            {copiedUrl ? "Copied!" : "Copy"}
                        </button>
                    </div>

                    {/* Open in new tab */}
                    <a
                        href={shareUrl!}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="flex items-center gap-2 text-xs text-white/40 hover:text-white/70 transition-colors"
                    >
                        <ExternalLink className="w-3 h-3" />
                        Preview share page
                    </a>

                    {/* Revoke */}
                    {!confirmRevoke ? (
                        <button
                            onClick={() => setConfirmRevoke(true)}
                            className="flex items-center gap-2 text-xs text-rose-400/60 hover:text-rose-400 transition-colors"
                        >
                            <Trash2 className="w-3 h-3" />
                            Revoke link
                        </button>
                    ) : (
                        <div className="flex items-center gap-2 p-3 rounded-xl bg-rose-500/[0.06] border border-rose-500/15">
                            <p className="flex-1 text-xs text-rose-300/80">Anyone with the current link will lose access.</p>
                            <button onClick={revoke} disabled={revoking} className="text-xs font-bold text-rose-400 hover:text-rose-300 disabled:opacity-50">
                                {revoking ? "Revoking…" : "Confirm"}
                            </button>
                            <button onClick={() => setConfirmRevoke(false)} className="text-xs text-white/30 hover:text-white/60">Cancel</button>
                        </div>
                    )}
                </div>
            )}

            {error && (
                <p className="text-xs text-rose-400/80 bg-rose-500/[0.06] border border-rose-500/15 rounded-lg px-3 py-2">{error}</p>
            )}
        </div>
    );
}

// ─── PDF tab ──────────────────────────────────────────────────────────────────

function PDFTab({ trip, rawItinerary }: { trip: TripDTO; rawItinerary: Itinerary | null }) {
    const days  = rawItinerary?.days.length ?? trip.itinerary.length;
    const acts  = rawItinerary?.days.reduce((s, d) => s + d.activities.length, 0) ?? 0;

    return (
        <div className="space-y-4">
            {/* Preview card */}
            <div className="rounded-xl border border-white/[0.07] bg-white/[0.02] p-5 space-y-4">
                <div className="flex items-start justify-between">
                    <div>
                        <p className="font-bold text-white">{trip.destination}</p>
                        <p className="text-xs text-white/40 mt-0.5">{trip.dates}</p>
                    </div>
                    <div className="text-right">
                        <p className="text-[10px] uppercase tracking-wider text-white/30 font-bold">Est. Cost</p>
                        <p className="text-lg font-black text-emerald-400">
                            {trip.budget.currency} {(rawItinerary?.totalEstimatedCost.amount ?? trip.budget.total).toLocaleString()}
                        </p>
                    </div>
                </div>
                <div className="flex gap-4 text-xs text-white/35">
                    <span>{days} day{days !== 1 ? "s" : ""}</span>
                    {acts > 0 && <span>{acts} activities</span>}
                </div>

                {/* Day mini-preview */}
                <div className="space-y-1.5 pt-2 border-t border-white/[0.05]">
                    {(rawItinerary?.days ?? []).slice(0, 3).map(day => (
                        <div key={day.day} className="flex items-center gap-2 text-xs">
                            <span className="w-5 h-5 rounded bg-emerald-500/15 text-emerald-400 font-bold flex items-center justify-center text-[10px] shrink-0">{day.day}</span>
                            <span className="text-white/50 truncate">{day.theme}</span>
                        </div>
                    ))}
                    {days > 3 && <p className="text-xs text-white/20 pl-7">+{days - 3} more days included</p>}
                </div>
            </div>

            <button
                onClick={() => triggerPrint(trip, rawItinerary)}
                className="w-full flex items-center justify-center gap-2 py-3 rounded-xl bg-white/[0.05] border border-white/[0.09] text-white/70 hover:text-white hover:bg-white/[0.09] text-sm font-semibold transition-colors"
            >
                <Printer className="w-4 h-4" />
                Open Print / Save as PDF
            </button>
            <p className="text-[10px] text-white/20 text-center">
                Opens a print-optimised page. Use your browser&apos;s &quot;Save as PDF&quot; option.
            </p>
        </div>
    );
}

// ─── Tab definitions ─────────────────────────────────────────────────────────

const TABS: { id: Tab; label: string; icon: React.ComponentType<{ className?: string }> }[] = [
    { id: "share",     label: "Share",     icon: Share2    },
    { id: "pdf",       label: "PDF",       icon: FileText  },
    { id: "instagram", label: "Instagram", icon: Instagram },
    { id: "blog",      label: "Blog",      icon: BookOpen  },
    { id: "summary",   label: "Summary",   icon: AlignLeft },
];

// ─── Main drawer ─────────────────────────────────────────────────────────────

export function ExportDrawer({ trip, rawItinerary, onClose }: ExportDrawerProps) {
    const [activeTab, setActiveTab] = useState<Tab>("share");

    // Build highlights for AI generation: top 2 activities per day
    const highlights: string[] = rawItinerary?.days.flatMap(day =>
        day.activities.slice(0, 2).map(a => `${a.name} (${a.location.name})`)
    ).slice(0, 12) ?? trip.itinerary.flatMap(day =>
        day.events.slice(0, 2).map(e => `${e.title} (${e.location})`)
    ).slice(0, 12);

    return (
        <>
            {/* Backdrop */}
            <motion.div
                key="export-backdrop"
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                exit={{ opacity: 0 }}
                transition={{ duration: 0.2 }}
                className="fixed inset-0 z-50 bg-black/50 backdrop-blur-sm"
                onClick={onClose}
            />

            {/* Drawer */}
            <motion.div
                key="export-drawer"
                initial={{ x: "100%" }}
                animate={{ x: 0 }}
                exit={{ x: "100%" }}
                transition={{ duration: 0.28, ease: [0.22, 1, 0.36, 1] as [number, number, number, number] }}
                className="fixed inset-y-0 right-0 z-50 w-full sm:w-[480px] bg-[#0E1318] border-l border-white/[0.08] shadow-2xl flex flex-col"
            >
                {/* Header */}
                <div className="flex items-center justify-between px-5 py-4 border-b border-white/[0.07] shrink-0">
                    <div className="flex items-center gap-2.5">
                        <div className="w-8 h-8 rounded-lg bg-emerald-500/15 border border-emerald-500/25 flex items-center justify-center">
                            <Share2 className="w-4 h-4 text-emerald-400" />
                        </div>
                        <div>
                            <p className="font-semibold text-white text-sm">Share & Export</p>
                            <p className="text-[10px] text-white/35">{trip.destination}</p>
                        </div>
                    </div>
                    <button
                        onClick={onClose}
                        className="w-8 h-8 rounded-xl bg-white/[0.04] border border-white/[0.06] flex items-center justify-center text-white/40 hover:text-white transition-colors"
                    >
                        <X className="w-4 h-4" />
                    </button>
                </div>

                {/* Tabs */}
                <div className="flex gap-0.5 px-4 pt-3 pb-1 shrink-0 overflow-x-auto scrollbar-none">
                    {TABS.map(tab => {
                        const Icon = tab.icon;
                        return (
                            <button
                                key={tab.id}
                                onClick={() => setActiveTab(tab.id)}
                                className={`flex items-center gap-1.5 px-3 py-2 rounded-lg text-xs font-semibold whitespace-nowrap transition-colors ${
                                    activeTab === tab.id
                                        ? "bg-white/[0.09] text-white"
                                        : "text-white/35 hover:text-white/60 hover:bg-white/[0.04]"
                                }`}
                            >
                                <Icon className="w-3.5 h-3.5" />
                                {tab.label}
                            </button>
                        );
                    })}
                </div>

                {/* Content */}
                <div className="flex-1 overflow-y-auto px-5 py-4">
                    <AnimatePresence mode="wait">
                        <motion.div
                            key={activeTab}
                            initial={{ opacity: 0, y: 8 }}
                            animate={{ opacity: 1, y: 0 }}
                            exit={{ opacity: 0, y: -4 }}
                            transition={{ duration: 0.15 }}
                        >
                            {activeTab === "share" && (
                                <ShareTab tripId={trip.id} />
                            )}
                            {activeTab === "pdf" && (
                                <PDFTab trip={trip} rawItinerary={rawItinerary} />
                            )}
                            {activeTab === "instagram" && (
                                <AIContentTab
                                    tripId={trip.id}
                                    format="instagram"
                                    destination={trip.destination}
                                    dates={trip.dates}
                                    days={rawItinerary?.totalDays ?? trip.itinerary.length}
                                    budget={trip.budget.total}
                                    currency={trip.budget.currency}
                                    highlights={highlights}
                                />
                            )}
                            {activeTab === "blog" && (
                                <div className="space-y-2">
                                    <div className="flex items-center gap-2 mb-3">
                                        <RefreshCw className="w-3.5 h-3.5 text-violet-400" />
                                        <p className="text-xs text-white/45">AI writes a full blog post — then you can edit it before copying.</p>
                                    </div>
                                    <AIContentTab
                                        tripId={trip.id}
                                        format="blog"
                                        destination={trip.destination}
                                        dates={trip.dates}
                                        days={rawItinerary?.totalDays ?? trip.itinerary.length}
                                        budget={trip.budget.total}
                                        currency={trip.budget.currency}
                                        highlights={highlights}
                                    />
                                </div>
                            )}
                            {activeTab === "summary" && (
                                <div className="space-y-2">
                                    <p className="text-xs text-white/40 mb-3">A short, shareable summary perfect for messaging friends or adding to notes.</p>
                                    <AIContentTab
                                        tripId={trip.id}
                                        format="summary"
                                        destination={trip.destination}
                                        dates={trip.dates}
                                        days={rawItinerary?.totalDays ?? trip.itinerary.length}
                                        budget={trip.budget.total}
                                        currency={trip.budget.currency}
                                        highlights={highlights}
                                    />
                                </div>
                            )}
                        </motion.div>
                    </AnimatePresence>
                </div>

                {/* Footer badge */}
                <div className="shrink-0 px-5 py-3 border-t border-white/[0.05] flex items-center justify-center gap-2">
                    <Sparkles className="w-3 h-3 text-white/20" />
                    <span className="text-[10px] text-white/20">Powered by VoyageAI</span>
                </div>
            </motion.div>
        </>
    );
}
